---
- hosts: main
  remote_user: root
  tasks:

  - include: tasks/management.yml

  - name: Copy deluged conf file
    copy:
      src: conf/deluged.conf
      dest: /etc/init/deluged.conf
    notify:
    - restart deluged

  - name: Copy deluge web conf file
    copy:
      src: conf/deluge-web.conf
      dest: /etc/init/deluge-web.conf
    notify:
    - restart deluged

  - name: ensure deluged is running (and enable it at boot)
    service: name=deluged state=started enabled=yes

  handlers:
    - name: restart deluged
      service: name=deluged state=restarted
