---
- hosts: main
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  tasks:
  - include: tasks/management.yml
  - include: tasks/users.yml
