---
- hosts: main
  remote_user: root
  tasks:

  - name: update apt cache
    apt: update_cache=yes cache_valid_time=3600

  - name: upgrade the distro
    apt: upgrade=yes

  - name: Add Deluge repo
    apt_repository: repo=ppa:deluge-team/ppa

  - name: install packages
    apt: pkg={{ item }} state=latest
    with_items:
     - zsh
     - deluge
     - deluged
     - deluge-web
    notify:
    - restart deluged

  - name: Create deluge group
    group:
      name: deluge
      state: present

  - name: Create deluge user
    user:
      name: deluge
      home: /var/lib/deluge
      system: yes
      group: deluge

  - name: Copy deluged conf file
    copy:
      src: conf/deluged.conf
      dest: /etc/init/deluged.conf
    notify:
    - restart deluged

  - name: Copy deluge web conf file
    copy:
      src: conf/deluge-web.conf
      dest: /etc/init/deluge-web.conf
    notify:
    - restart deluged

  - name: ensure deluged is running (and enable it at boot)
    service: name=deluged state=started enabled=yes

  handlers:
    - name: restart deluged
      service: name=deluged state=restarted
