---

# Tasks related to creating users and groups

- name: Create deluge group
  group:
    name: deluge
    state: present

- name: Create deluge user
  user:
    name: deluge
    home: /var/lib/deluge
    system: yes
    group: deluge
